---

- name: Install and configure IMPSy
  hosts: impsypi
  tasks:

  - name: apt update
    become: true
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: apt upgrade
    become: true
    apt:
      upgrade: dist

  - name: Install packages
    become: true
    apt:
      pkg:
        - libhdf5-dev
        - unzip
        - pkg-config
        - python3-pip
        - cmake
        - make
        - git
        - python-is-python3
        - wget
        - patchelf
        - pipx

  - name: Install Poetry
    # become: true
    community.general.pipx: 
      name: poetry 

  - name: Git checkout IMPSY
    ansible.builtin.git:
      repo: 'https://github.com/cpmpercussion/imps.git'
      dest: '{{ ansible_env.HOME }}/imps'
      version: main

  - name: Poetry Install IMPSY
    command: poetry install
    args:
      chdir: '{{ ansible_env.HOME }}/imps'
    environment: 
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin'

  - name: Poetry test run IMPSY
    command: poetry run ./start_impsy.py test-mdrnn
    args:
      chdir: '{{ ansible_env.HOME }}/imps'
    environment:
      PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin'

  - name: Create IMPSY-run service
    become: true
    template:
      src: templates/impsy-run.service.j2
      dest: /etc/systemd/system/impsy-run.service

  - name: Create IMPSY-web service
    become: true
    template:
      src: templates/impsy-web.service.j2
      dest: /etc/systemd/system/impsy-web.service

  - name: Start IMPSY-web service
    become: true
    systemd:
      name: impsy-web.service
      daemon_reload: true
      state: started
      enabled: true

  - name: Start IMPSY-run service
    become: true
    systemd:
      name: impsy-run.service
      state: started
      enabled: true
