---

- name: install-impsy
- hosts: raspi
  tasks:

  - name: apt update
    become: true
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: apt upgrade
    become: true
    apt:
      upgrade: dist

  - name: Install packages
    become: true
    apt:
      pkg:
        - libhdf5-dev
        - unzip
        - pkg-config
        - python3-pip
        - cmake
        - make
        - git
        - python-is-python3
        - wget
        - patchelf
        - pipx

  - name: Install Poetry
    # become: true
    community.general.pipx: 
      name: poetry 

  - name: Git checkout IMPSY
    ansible.builtin.git:
      repo: 'https://github.com/cpmpercussion/imps.git'
      dest: "{{ ansible_env.HOME }}/imps"
      version: main

  - name: Poetry Install IMPSY
    command: poetry install
    args:
      chdir: "{{ ansible_env.HOME }}/imps"
    environment: 
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin'

  - name: Poetry test run IMPSY
    command: poetry run ./start_impsy.py test-mdrnn
    args:
      chdir: "{{ ansible_env.HOME }}/imps"
    environment:
      PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin'

# {{ ansible_env.HOME }}/.local/bin

  # - name: Add ~/.local/bin to .bashrc
  #   blockinfile:
  #     dest: "{{ ansible_env.HOME }}/.bashrc"
  #     block: |
  #       export PATH="$HOME/.local/bin:$PATH"
  #     marker: '# {mark} ANSIBLE MANAGED BLOCK - pipx'
  #     create: yes

  # - name: Run pipx ensurepath
  #   shell: pipx ensurepath
  #   environment: 
  #     PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin'